"""
Detection signal functions for Provenance Guard.

Each signal function takes raw text and returns a float between 0 and 1,
where 0 = confidently human-written and 1 = confidently AI-generated.
"""

import os
import json
from groq import Groq
from dotenv import load_dotenv

load_dotenv()  # reads .env in the project root and loads it into os.environ

# Reads your key from the environment (via .env or an actual export).
# Client is created lazily so a missing key doesn't crash the app at import
# time -- it only fails when signal_1_llm_judge is actually called, and that
# failure is caught below and turned into a neutral 0.5 score.
_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
    return _client

SIGNAL_1_SYSTEM_PROMPT = """You are a text analysis tool that estimates the likelihood a piece of writing was generated by an AI language model versus written by a human.

Look for patterns like: generic transitional phrases (e.g. "it is important to note," "furthermore," "in conclusion"), hedged-but-confident phrasing, unusually uniform sentence and paragraph structure, and a lack of specific personal detail or idiosyncrasy.

Respond ONLY with a JSON object in this exact format, no other text:
{"score": <float between 0 and 1>, "reasoning": "<one sentence explanation>"}

A score of 0 means confidently human-written. A score of 1 means confidently AI-generated."""


def signal_1_llm_judge(text: str) -> dict:
    """
    Calls Groq to get an LLM-based judgment on whether text is AI-generated.

    Returns a dict: {"score": float, "reasoning": str}
    On API failure, returns a neutral score of 0.5 so the pipeline doesn't
    crash on a single signal outage.
    """
    try:
        response = _get_client().chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SIGNAL_1_SYSTEM_PROMPT},
                {"role": "user", "content": f"Analyze this text:\n\n{text}"},
            ],
            temperature=0.2,
            max_tokens=200,
        )
        raw = response.choices[0].message.content.strip()
        parsed = json.loads(raw)
        score = float(parsed.get("score", 0.5))
        # clamp defensively in case the model returns something out of range
        score = max(0.0, min(1.0, score))
        return {"score": score, "reasoning": parsed.get("reasoning", "")}
    except Exception as e:
        print(f"[signal_1_llm_judge] error: {e}")
        return {"score": 0.5, "reasoning": f"signal_1_failed: {e}"}


if __name__ == "__main__":
    # Quick standalone test. Run: python signals.py
    test_inputs = [
        ("clearly_ai", (
            "Artificial intelligence represents a transformative paradigm shift in modern "
            "society. It is important to note that while the benefits of AI are numerous, "
            "it is equally essential to consider the ethical implications. Furthermore, "
            "stakeholders across various sectors must collaborate to ensure responsible "
            "deployment."
        )),
        ("clearly_human", (
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium in it and "
            "i was thirsty for like three hours after. my friend got the spicy version and "
            "said it was better. probably won't go back unless someone drags me there"
        )),
    ]

    for label, text in test_inputs:
        result = signal_1_llm_judge(text)
        print(f"{label}: score={result['score']:.2f} | {result['reasoning']}")