"""
Detection signal functions for Provenance Guard.

Each signal function takes raw text and returns a float between 0 and 1,
where 0 = confidently human-written and 1 = confidently AI-generated.
"""

import os
import json
import re
import statistics
from groq import Groq
from dotenv import load_dotenv

load_dotenv()  # reads .env in the project root and loads it into os.environ

# Reads your key from the environment (via .env or an actual export).
# Client is created lazily so a missing key doesn't crash the app at import
# time -- it only fails when signal_1_llm_judge is actually called, and that
# failure is caught below and turned into a neutral 0.5 score.
_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
    return _client

SIGNAL_1_SYSTEM_PROMPT = """You are a text analysis tool that estimates the likelihood a piece of writing was generated by an AI language model versus written by a human.

Look for patterns like: generic transitional phrases (e.g. "it is important to note," "furthermore," "in conclusion"), hedged-but-confident phrasing, unusually uniform sentence and paragraph structure, and a lack of specific personal detail or idiosyncrasy.

Respond ONLY with a JSON object in this exact format, no other text:
{"score": <float between 0 and 1>, "reasoning": "<one sentence explanation>"}

A score of 0 means confidently human-written. A score of 1 means confidently AI-generated."""


def signal_1_llm_judge(text: str) -> dict:
    """
    Calls Groq to get an LLM-based judgment on whether text is AI-generated.

    Returns a dict: {"score": float, "reasoning": str}
    On API failure, returns a neutral score of 0.5 so the pipeline doesn't
    crash on a single signal outage.
    """
    try:
        response = _get_client().chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SIGNAL_1_SYSTEM_PROMPT},
                {"role": "user", "content": f"Analyze this text:\n\n{text}"},
            ],
            temperature=0.2,
            max_tokens=200,
        )
        raw = response.choices[0].message.content.strip()
        parsed = json.loads(raw)
        score = float(parsed.get("score", 0.5))
        # clamp defensively in case the model returns something out of range
        score = max(0.0, min(1.0, score))
        return {"score": score, "reasoning": parsed.get("reasoning", "")}
    except Exception as e:
        print(f"[signal_1_llm_judge] error: {e}")
        return {"score": 0.5, "reasoning": f"signal_1_failed: {e}"}


def _split_sentences(text: str) -> list:
    """Naive sentence splitter on . ! ? -- good enough for stylometrics, not linguistics."""
    sentences = re.split(r"[.!?]+", text)
    return [s.strip() for s in sentences if s.strip()]


def _sentence_length_variance_score(text: str) -> float:
    """
    Computes variance in sentence length (words per sentence), then maps it
    to a 0-1 score where LOW variance -> HIGH score (AI-like: uniform
    sentence structure) and HIGH variance -> LOW score (human-like: bursty,
    irregular sentence lengths).

    Normalization assumption: a stdev of 0 words maps to 1.0 (max AI-like),
    a stdev of 8+ words maps to 0.0 (max human-like). 8 was picked as a
    rough ceiling based on eyeballing the test inputs below -- documented
    here as an assumption to revisit if real submissions skew the range.
    """
    sentences = _split_sentences(text)
    if len(sentences) < 2:
        # Can't compute variance from a single sentence; return neutral.
        return 0.5

    lengths = [len(s.split()) for s in sentences]
    stdev = statistics.stdev(lengths)

    MAX_STDEV_CEILING = 8.0
    normalized = 1.0 - min(stdev / MAX_STDEV_CEILING, 1.0)
    return normalized


def _type_token_ratio_score(text: str) -> float:
    """
    Computes type-token ratio (unique words / total words), then maps it to
    a 0-1 AI-likeness score where LOW diversity -> HIGH score (AI-like) and
    HIGH diversity -> LOW score (human-like).

    Known limitation (documented in planning.md edge cases): TTR is noisy
    on short text (under ~100 words), since a handful of unique words in a
    short sample produces an unreliable ratio either direction.
    """
    words = re.findall(r"[a-zA-Z']+", text.lower())
    if len(words) < 5:
        return 0.5  # not enough text to say anything meaningful

    ttr = len(set(words)) / len(words)
    # ttr is already 0-1; invert it so low diversity -> high AI-likeness score
    return 1.0 - ttr


def signal_2_stylometric(text: str) -> dict:
    """
    Computes a stylometric AI-likeness score from sentence length variance
    and type-token ratio, no external API call.

    Returns a dict: {"score": float, "reasoning": str}
    """
    variance_score = _sentence_length_variance_score(text)
    ttr_score = _type_token_ratio_score(text)
    combined = (variance_score + ttr_score) / 2
    combined = max(0.0, min(1.0, combined))

    reasoning = (
        f"sentence-length-uniformity={variance_score:.2f}, "
        f"low-vocabulary-diversity={ttr_score:.2f}"
    )
    return {"score": combined, "reasoning": reasoning}


if __name__ == "__main__":
    # Quick standalone test. Run: python signals.py
    test_inputs = [
        ("clearly_ai", (
            "Artificial intelligence represents a transformative paradigm shift in modern "
            "society. It is important to note that while the benefits of AI are numerous, "
            "it is equally essential to consider the ethical implications. Furthermore, "
            "stakeholders across various sectors must collaborate to ensure responsible "
            "deployment."
        )),
        ("clearly_human", (
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium in it and "
            "i was thirsty for like three hours after. my friend got the spicy version and "
            "said it was better. probably won't go back unless someone drags me there"
        )),
        ("borderline_formal_human", (
            "The relationship between monetary policy and asset price inflation has been "
            "extensively studied in the literature. Central banks face a fundamental tension "
            "between their mandate for price stability and the unintended consequences of "
            "prolonged low interest rates on equity and real estate valuations."
        )),
        ("borderline_edited_ai", (
            "I've been thinking a lot about remote work lately. There are genuine tradeoffs "
            "-- flexibility and no commute on one side, isolation and blurred work-life "
            "boundaries on the other. Studies show productivity varies widely by individual "
            "and role type."
        )),
    ]

    print("=== Signal 1 (LLM judge) ===")
    for label, text in test_inputs:
        result = signal_1_llm_judge(text)
        print(f"{label}: score={result['score']:.2f} | {result['reasoning']}")

    print("\n=== Signal 2 (stylometric) ===")
    for label, text in test_inputs:
        result = signal_2_stylometric(text)
        print(f"{label}: score={result['score']:.2f} | {result['reasoning']}")